type PublicEnv = {
  EXPO_PUBLIC_API_URL?: string;
  EXPO_PUBLIC_FIREBASE_API_KEY?: string;
  EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN?: string;
  EXPO_PUBLIC_FIREBASE_PROJECT_ID?: string;
  EXPO_PUBLIC_FIREBASE_APP_ID?: string;
  EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID?: string;
  EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID?: string;
  EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID?: string;
};

const fallbackPublicEnv: PublicEnv = {
  EXPO_PUBLIC_API_URL: 'http://10.0.2.2:3000',
  EXPO_PUBLIC_FIREBASE_API_KEY: 'AIzaSyDUmUqZ5FSeamLS7YZstJspviSLcOTz6qo',
  EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN: 'tv-app-9dffd.firebaseapp.com',
  EXPO_PUBLIC_FIREBASE_PROJECT_ID: 'tv-app-9dffd',
  EXPO_PUBLIC_FIREBASE_APP_ID: '1:976365509331:ios:df8295f700a959e2099226',
  EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID:
    '976365509331-4tt3jqmfvven63n9bnq2bgv0n4eajjnc.apps.googleusercontent.com',
  EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID:
    '976365509331-hqmc9fs6br68ht4tkf83mej76cd9mohn.apps.googleusercontent.com',
};

export const publicEnv: PublicEnv = {
  EXPO_PUBLIC_API_URL: process.env.EXPO_PUBLIC_API_URL ?? fallbackPublicEnv.EXPO_PUBLIC_API_URL,
  EXPO_PUBLIC_FIREBASE_API_KEY:
    process.env.EXPO_PUBLIC_FIREBASE_API_KEY ?? fallbackPublicEnv.EXPO_PUBLIC_FIREBASE_API_KEY,
  EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN:
    process.env.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN ?? fallbackPublicEnv.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN,
  EXPO_PUBLIC_FIREBASE_PROJECT_ID:
    process.env.EXPO_PUBLIC_FIREBASE_PROJECT_ID ?? fallbackPublicEnv.EXPO_PUBLIC_FIREBASE_PROJECT_ID,
  EXPO_PUBLIC_FIREBASE_APP_ID:
    process.env.EXPO_PUBLIC_FIREBASE_APP_ID ?? fallbackPublicEnv.EXPO_PUBLIC_FIREBASE_APP_ID,
  EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID:
    process.env.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID ?? fallbackPublicEnv.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID,
  EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID:
    process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID ?? fallbackPublicEnv.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID,
  EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID:
    process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID ?? fallbackPublicEnv.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID,
};
