import { resolveAppEnvironment, validatePublicEnvironment } from './appEnvironment';

type PublicEnv = {
  EXPO_PUBLIC_APP_ENV?: string;
  EXPO_PUBLIC_API_URL?: string;
  EXPO_PUBLIC_ERROR_TRACKING_DSN?: string;
  EXPO_PUBLIC_FIREBASE_API_KEY?: string;
  EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN?: string;
  EXPO_PUBLIC_FIREBASE_PROJECT_ID?: string;
  EXPO_PUBLIC_FIREBASE_APP_ID?: string;
  EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID?: string;
  EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID?: string;
  EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID?: string;
  EXPO_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST?: string;
  EXPO_PUBLIC_UI_REVIEW_EMAIL?: string;
  EXPO_PUBLIC_UI_REVIEW_PASSWORD?: string;
};

export const appEnvironment = resolveAppEnvironment(process.env.EXPO_PUBLIC_APP_ENV);

const developmentFallbackPublicEnv: PublicEnv = {
  EXPO_PUBLIC_API_URL: 'http://10.0.2.2:3000',
  EXPO_PUBLIC_FIREBASE_API_KEY: 'AIzaSyDUmUqZ5FSeamLS7YZstJspviSLcOTz6qo',
  EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN: 'tv-app-9dffd.firebaseapp.com',
  EXPO_PUBLIC_FIREBASE_PROJECT_ID: 'tv-app-9dffd',
  EXPO_PUBLIC_FIREBASE_APP_ID: '1:976365509331:ios:df8295f700a959e2099226',
  EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID:
    '976365509331-4tt3jqmfvven63n9bnq2bgv0n4eajjnc.apps.googleusercontent.com',
  EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID:
    '976365509331-hqmc9fs6br68ht4tkf83mej76cd9mohn.apps.googleusercontent.com',
};

const fallbackPublicEnv = appEnvironment === 'development' ? developmentFallbackPublicEnv : {};

export const publicEnv: PublicEnv = {
  EXPO_PUBLIC_APP_ENV: process.env.EXPO_PUBLIC_APP_ENV ?? appEnvironment,
  EXPO_PUBLIC_API_URL: process.env.EXPO_PUBLIC_API_URL ?? fallbackPublicEnv.EXPO_PUBLIC_API_URL,
  EXPO_PUBLIC_ERROR_TRACKING_DSN: process.env.EXPO_PUBLIC_ERROR_TRACKING_DSN,
  EXPO_PUBLIC_FIREBASE_API_KEY:
    process.env.EXPO_PUBLIC_FIREBASE_API_KEY ?? fallbackPublicEnv.EXPO_PUBLIC_FIREBASE_API_KEY,
  EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN:
    process.env.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN ?? fallbackPublicEnv.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN,
  EXPO_PUBLIC_FIREBASE_PROJECT_ID:
    process.env.EXPO_PUBLIC_FIREBASE_PROJECT_ID ?? fallbackPublicEnv.EXPO_PUBLIC_FIREBASE_PROJECT_ID,
  EXPO_PUBLIC_FIREBASE_APP_ID:
    process.env.EXPO_PUBLIC_FIREBASE_APP_ID ?? fallbackPublicEnv.EXPO_PUBLIC_FIREBASE_APP_ID,
  EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID:
    process.env.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID ?? fallbackPublicEnv.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID,
  EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID:
    process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID ?? fallbackPublicEnv.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID,
  EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID:
    process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID ?? fallbackPublicEnv.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID,
  EXPO_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST: process.env.EXPO_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST,
  EXPO_PUBLIC_UI_REVIEW_EMAIL: process.env.EXPO_PUBLIC_UI_REVIEW_EMAIL,
  EXPO_PUBLIC_UI_REVIEW_PASSWORD: process.env.EXPO_PUBLIC_UI_REVIEW_PASSWORD,
};

validatePublicEnvironment(appEnvironment, {
  apiUrl: publicEnv.EXPO_PUBLIC_API_URL,
  errorTrackingDsn: publicEnv.EXPO_PUBLIC_ERROR_TRACKING_DSN,
  firebaseApiKey: publicEnv.EXPO_PUBLIC_FIREBASE_API_KEY,
  firebaseAppId: publicEnv.EXPO_PUBLIC_FIREBASE_APP_ID,
  firebaseAuthDomain: publicEnv.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN,
  firebaseAuthEmulatorHost: publicEnv.EXPO_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST,
  firebaseProjectId: publicEnv.EXPO_PUBLIC_FIREBASE_PROJECT_ID,
  uiReviewEmail: publicEnv.EXPO_PUBLIC_UI_REVIEW_EMAIL,
  uiReviewPassword: publicEnv.EXPO_PUBLIC_UI_REVIEW_PASSWORD,
});
