import assert from 'node:assert/strict';
import { beginTitleRemoval, isTitleRemoved } from './titleRemovalUpdates';

const movie = { contentType: 'movie' as const, tmdbId: 550 };
const series = { contentType: 'series' as const, tmdbId: 550 };
const before = Date.now();
const first = beginTitleRemoval('owner', 'profile', movie, true)!;
assert(isTitleRemoved('owner', 'profile', movie));
assert(isTitleRemoved('owner', 'personal:planned', movie, 0, true));
assert(!isTitleRemoved('owner', 'personal:custom', movie));
assert(!isTitleRemoved('other', 'profile', movie));
assert(!isTitleRemoved('owner', 'profile', series));
assert.equal(beginTitleRemoval('owner', 'profile', movie, true), null, 'duplicate pending deletion must not send another request');
const second = beginTitleRemoval('owner', 'profile', series, true)!;
first.rollback();
assert(!isTitleRemoved('owner', 'profile', movie));
assert(isTitleRemoved('owner', 'profile', series), 'rolling back one title must preserve other pending removals');
second.commit();
assert(isTitleRemoved('owner', 'profile', series, before), 'a late stale response must not resurrect a deleted title');
second.rollback();
assert(isTitleRemoved('owner', 'profile', series), 'cache failure after server success cannot undo a deletion');
assert(!isTitleRemoved('owner', 'profile', series, Date.now() + 1), 'a fresh response can show a deliberately re-added title');
const list = beginTitleRemoval('owner', 'shared:one', movie, false)!;
assert(isTitleRemoved('owner', 'shared:one', movie));
assert(!isTitleRemoved('owner', 'shared:two', movie));
assert(!isTitleRemoved('owner', 'profile', movie));
list.rollback();
assert(!isTitleRemoved('owner', 'shared:one', movie));
console.log('Optimistic title removal QA passed: immediate hiding, owner/type/list isolation, concurrent rollback and stale responses.');
