import { Pressable, StyleSheet, Text, View } from 'react-native';
import { MediaPoster } from '../components/MediaPoster';
import { StarRatingDisplay } from '../components/StarRatingDisplay';
import { colors, radii, spacing, typography } from '../design/tokens';
import type { HydratedJournalEntry } from './JournalScreen';

export function JournalEntryCard({ entry, onPress }: { entry: HydratedJournalEntry; onPress: () => void }) {
  return <View style={styles.timelineRow}><View style={styles.dot} /><View style={styles.entry}><Text style={styles.date}>{formatDate(entry.date)}</Text><Pressable accessibilityLabel={`Open ${entry.title}`} accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><MediaPoster posterUrl={entry.posterUrl} style={styles.poster} /><View style={styles.copy}><Text style={styles.eyebrow}>{entry.kind === 'movie' ? 'MOVIE WATCHED' : `SERIES · ${entry.episodes.length} EPISODES`}</Text><Text numberOfLines={2} style={styles.title}>{entry.title}</Text>{entry.ratingScore !== null ? <StarRatingDisplay rating={entry.ratingScore} showValue size={16} /> : null}{entry.kind === 'series' && entry.episodes.length ? <View style={styles.episodes}>{entry.episodes.slice(0, 5).map((episode) => <View key={`${episode.seasonNumber}:${episode.episodeNumber}`} style={styles.episode}><Text style={styles.episodeText}>E{episode.episodeNumber}</Text></View>)}{entry.episodes.length > 5 ? <Text style={styles.more}>+{entry.episodes.length - 5}</Text> : null}</View> : null}{entry.reviewBody ? <Text numberOfLines={4} style={styles.review}>{entry.reviewBody}</Text> : null}</View></Pressable></View></View>;
}
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : date.toLocaleDateString('en-US', { day: 'numeric', month: 'long' }); }
const styles = StyleSheet.create({ timelineRow: { borderLeftColor: colors.border, borderLeftWidth: 1, marginLeft: 5, paddingBottom: spacing.lg, paddingLeft: spacing.lg, position: 'relative' }, dot: { backgroundColor: colors.background, borderColor: colors.accent, borderRadius: 5, borderWidth: 2, height: 10, left: -5.5, position: 'absolute', top: 7, width: 10 }, entry: { gap: spacing.xs }, date: { color: colors.textSubtle, fontSize: 11 }, card: { backgroundColor: colors.panel, borderColor: colors.border, borderRadius: radii.lg, borderWidth: 1, flexDirection: 'row', gap: spacing.md, padding: spacing.sm }, poster: { borderRadius: radii.sm, height: 84, width: 56 }, copy: { flex: 1, gap: 4, minWidth: 0 }, eyebrow: { ...typography.eyebrow, color: colors.accentText, fontSize: 10 }, title: { color: colors.text, fontSize: 15, fontWeight: '800' }, episodes: { alignItems: 'center', flexDirection: 'row', marginTop: 3 }, episode: { alignItems: 'center', backgroundColor: colors.panelElevated, borderColor: colors.panel, borderRadius: 14, borderWidth: 2, height: 28, justifyContent: 'center', marginRight: -4, width: 28 }, episodeText: { color: colors.textMuted, fontSize: 9, fontWeight: '700' }, more: { color: colors.textSubtle, fontSize: 10, marginLeft: 8 }, review: { ...typography.body, borderLeftColor: colors.borderStrong, borderLeftWidth: 2, color: colors.textMuted, fontSize: 12, lineHeight: 17, marginTop: spacing.xs, paddingLeft: spacing.sm }, pressed: { opacity: 0.78 } });
